markdown: kramdown
redcarpet:
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:
permalink: none
exclude:
  - "en-US/images/precompressed/"
  - "ebook/gitbook-zh-CN"
  - "ebook/gitbook-en-US"
  - "ebook/gitbook-fr-FR"
  - "ebook/gitbook-fa-IR"
  - "ebook/gitbook-ja-JP"
  - "ebook/gitbook-pt-BR"
  - "ebook/gitbook-de-DE"
  - "ebook/cover_small_template.svg"
  - "ebook/cover_template.svg"
  - "ebook/create_books.sh"
  - "ebook/honkit-en-US"
  - "ebook/honkit-fr-FR"
  - "ebook/honkit-ja-JP"
  - "ebook/honkit-zh-CN"
  - "ebook/honkit-pt-BR"
  - "ebook/honkit-de-DE"
  - "ebook/package-lock.json"
  - "ebook/package.json"
  - "ebook/temp"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
url: http://designwithfontforge.com
title: Design With FontForge
title_de-DE: Entwerfen Sie mit FontForge
title_fa-IR: طراحی با فونت‌فورج
title_fr-FR: Design avec FontForge
title_ja-JP: Design With FontForge
title_pt-BR: Design com FontForge
title_zh-CN: FontForge 与字体设计
title_zh-TW: FontForge 與字體設計
subtitle: A book about how to create new typefaces using FontForge
subtitle_de-DE: A book about how to create new typefaces using FontForge
subtitle_fa-IR: کتابی درباره چگونگی ساخت یک تایپ‌فیس جدید با کمک فونت‌فورج
subtitle_fr-FR: Un livre sur la création de polices à l'aide de FontForge
subtitle_ja-JP: A book about how to create new typefaces using FontForge
subtitle_pt-BR: Um livro sobre como criar novos tipos usando FontForge
subtitle_zh-CN: 介绍如何使用 FontForge 创造新字体的书
subtitle_zh-TW: 介紹以 FontForge 製作新字型的書

